/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        sidebar: "var(--sidebar)",
        paper: "#F5F1E8",
        "paper-2": "#FBF8F1",
        ink: "#17140F",
        "ink-soft": "#4A443C",
        rule: "#DCD5C6",
        tangerine: "#E8471A",
        lime: "#C7DD52",
        sky: "#A6C9EC",
        peach: "#FFC6A6",
        blush: "#F3A0B8",
      },
      fontFamily: {
        display: ['"Instrument Serif"', "Georgia", "serif"],
        hand: ["Caveat", "cursive"],
        mono: ['"Space Mono"', "ui-monospace", "monospace"],
        sans: ['"DM Sans"', "ui-sans-serif", "system-ui"],
      },
      boxShadow: {
        paper: "4px 6px 0 rgba(23,20,15,0.10)",
        "paper-lg": "10px 14px 0 rgba(23,20,15,0.12)",
      },
    },
  },
  plugins: [],
};
